# Generated by Django 5.1.4 on 2024-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0002_profile_coordinatordetail_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emial',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
